{
 "title": "Node Dashboard Stardust",
 "description": "Dashboard for the IOTA node software",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "message_type",
    "query": {
     "query": "label_values(iota_gossip_node_message_count, type)"
    }
   },
   {
    "name": "peers",
    "query": {
     "query": "label_values(iota_gossip_peers_message_count, id)"
    }
   },
   {
    "name": "peer_message_type",
    "query": {
     "query": "label_values(iota_gossip_peers_message_count, type)"
    }
   },
   {
    "name": "peer_request_type",
    "query": {
     "query": "label_values(iota_gossip_peers_request_count, type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "description": "Node Version",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "iota_node_app_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "iota_node_health" }
   ]
  },
  {
   "type": "stat",
   "description": "The sync status of the node",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(iota_node_milestones{type=\"latest\"} - on () iota_node_milestones{type=\"confirmed\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "BPS in the last hour",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "BPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(iota_node_blocks_per_second[1h]))"
    }
   ]
  },
  {
   "type": "stat",
   "description": "BPS in the last 10 minutes",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "BPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(iota_node_blocks_per_second[10m]))"
    }
   ]
  },
  {
   "type": "stat",
   "description": "BPS in the last day",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "BPS" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(iota_node_blocks_per_second[1d]))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime of the node",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time()-container_start_time_seconds{name=\"hornet\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "CPU usage",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"hornet\"}[5m]))/sum(machine_cpu_cores)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "RAM usage",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=\"hornet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UTXO database size",
   "type": "stat",
   "description": "Size of the ledger database",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_database_utxo_size_bytes{}"
    }
   ]
  },
  {
   "title": "Tangle database size",
   "type": "stat",
   "description": "Size of the tangle database",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_database_tangle_size_bytes{}"
    }
   ]
  },
  {
   "title": "Neighbors",
   "type": "stat",
   "description": "Neighbors count",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(iota_gossip_peers_connected_peers{})"
    }
   ]
  },
  {
   "title": "Milestones",
   "type": "stat",
   "description": "Milestone stats",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_node_milestones{}", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Conf.Ratio",
   "type": "stat",
   "description": "Ratio of referenced blocks in relation to new blocks of the last confirmed milestone.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(iota_node_referenced_rate{})"
    }
   ]
  },
  {
   "title": "Current",
   "type": "gauge",
   "description": "Current BPS",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "BPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_node_blocks_per_second{}" }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "description": "Size of the databases",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "iota_database_tangle_size_bytes{}",
     "legendFormat": "Tangle"
    },
    {
     "expr": "iota_database_utxo_size_bytes{}",
     "legendFormat": "Ledger"
    }
   ]
  },
  {
   "title": "Tips",
   "type": "stat",
   "description": "Amount of tips per second",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_node_tips{}", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "CPU usage per container",
   "type": "timeseries",
   "description": "CPU usage of every single container running",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (name) (rate(container_cpu_usage_seconds_total{name=~\".+\"}[5m]))) / scalar(machine_cpu_cores) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "timeseries",
   "description": "Memory usage of every single container running",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Caches Size",
     "type": "timeseries",
     "description": "Cache sizes per type",
     "gridPos": { "h": 8, "w": 21, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "iota_caches_size{}", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "Is compacting/pruning",
     "type": "stat",
     "description": "Pruning and compaction status",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "iota_database_utxo_compaction_running{} or iota_database_tangle_compaction_running{}",
       "legendFormat": "Compacting"
      },
      {
       "expr": "iota_database_pruning_running{}",
       "legendFormat": "Pruning"
      }
     ]
    },
    {
     "title": "Compaction / pruning counts",
     "type": "stat",
     "description": "Compaction and pruning counts",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "iota_database_utxo_compaction_count_total{}+iota_database_tangle_compaction_count_total{}",
       "legendFormat": "Compaction"
      },
      {
       "expr": "iota_database_pruning_count_total{}",
       "legendFormat": "Pruning"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocks per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "iota_node_blocks_per_second{}", "legendFormat": "BPS" }
     ]
    },
    {
     "title": "Requests per second",
     "type": "timeseries",
     "description": "Requests per second per type",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(iota_node_block_requests{type=\"pending\"}[1m])",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "irate(iota_node_block_requests{type=\"queued\"}[1m])",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "irate(iota_node_block_requests{type=\"processing\"}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Blocks per second per peer",
     "type": "timeseries",
     "description": "BPS per peer per type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (id) (rate(iota_gossip_peers_blocks{}[1m]))",
       "legendFormat": "{{id}} - {{type}}"
      }
     ]
    },
    {
     "title": "Requests per second per peer",
     "type": "timeseries",
     "description": "Requests per second per peer",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (id) (rate(iota_gossip_peers_requests{}[1m]))",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Heartbeats per second",
     "type": "timeseries",
     "description": "Heartbeats per second",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "rate(iota_gossip_node_heartbeats[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Dropped packages",
     "type": "timeseries",
     "description": "Sum of dropped packages",
     "gridPos": { "h": 8, "w": 4, "x": 5, "y": 43 },
     "targets": [
      {
       "expr": "rate(iota_gossip_node_dropped_packets{}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Sent heartbeats per peer",
     "type": "timeseries",
     "description": "Distribution of sent heartbeats per peer",
     "gridPos": { "h": 8, "w": 5, "x": 9, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(iota_gossip_peers_heartbeats{type=~\"sent\"}[1m])",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Received heartbeats per peer",
     "type": "timeseries",
     "description": "Distribution of received heartbeats per peer",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(iota_gossip_peers_heartbeats{type=~\"received\"}[1m])",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Dropped packages per peer",
     "type": "timeseries",
     "description": "Distribution of dropped packages per peer",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(iota_gossip_peers_dropped_packets{type=\"sent\"}[1m])",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "API requests by code / URL",
     "type": "timeseries",
     "description": "Distribution of dropped packages per peer",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "(label_replace(rate(iota_restapi_requests_total[1m]),\"short_url\",\"$1$2$3\",\"url\",'(.*)'))",
       "legendFormat": "{{code}} {{short_url}}"
      }
     ]
    },
    {
     "title": "HTTP request errors",
     "type": "timeseries",
     "description": "HTTP request errors",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 52 },
     "targets": [
      {
       "expr": "iota_restapi_http_request_errors{}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Traefik requests ( Success + / Error - )",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "rate(traefik_service_requests_total{service=\"hornet@docker\"}[1m])",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "PoW requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "targets": [
      { "expr": "iota_inx_pow_requests{}", "legendFormat": "INX" },
      { "expr": "iota_restapi_pow_requests{}", "legendFormat": "REST API" }
     ]
    }
   ]
  },
  {
   "title": "Migrator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receipts metrics",
     "type": "timeseries",
     "description": "Stats for the migration receipts",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "iota_migrator_receipt_count_total{}",
       "legendFormat": "Receipt Count"
      },
      {
       "expr": "iota_migrator_receipt_entries_applied_count_total{}",
       "legendFormat": "Receipt Entries Applied Count"
      }
     ]
    }
   ]
  }
 ]
}